### ISSUE TITLE
每日任务似乎无法领取到荧光棒

### ISSUE THREAD

**Issue by u2shana** [starudream/douyu-task#24]
将每周任务设置在每日任务当天后面执行

看日志，每日任务已经登录成功并且输出了所有牌子信息

但是接下来的每周任务执行时还是提示背包没有礼物

**Comment by starudream** [comment]
我原以为是调用接口就会获得荧光棒，后面看到 https://github.com/pelucky/DouyuDanmu/issues/4#issuecomment-453519535 才知道要 websocket 登录才行。

[v1.8.0](https://github.com/starudream/douyu-task/releases/tag/v1.8.0) 版本昨天测试已通过。
