### ISSUE TITLE
刷新背包websocket登陆报错是什么原因呢

### ISSUE THREAD

**Issue by u2shana** [starudream/douyu-task#25]
![image](https://github.com/starudream/douyu-task/assets/14146754/36f1eb76-d06f-45f9-8880-58bf558f31cd)
已经很注意yaml文件的编码和空白字符了，但还是报错

其他功能都登陆正常

**Comment by D3ee** [comment]
+1,是用了这个以后不能看直播了吗？

**Comment by starudream** [comment]
> ![image](https://user-images.githubusercontent.com/14146754/253714036-36f1eb76-d06f-45f9-8880-58bf558f31cd.png) 已经很注意yaml文件的编码和空白字符了，但还是报错
> 
> 其他功能都登陆正常

这个功能当时我只在本地做了测试，感觉是添加的参数好像只能用一次而且有过期限制。
新版本通过登录 `refresh` 接口重新获取这些参数。

https://github.com/starudream/douyu-task/releases/tag/v2.0.0 这个版本用 `douyu-task run login` 试一下看看。

**Comment by starudream** [comment]
> +1,是用了这个以后不能看直播了吗？

其他终端看直播，使用这个功能会踢掉当前终端，重新进一下直播间就好。

**Comment by u2shana** [comment]
> > ![image](https://user-images.githubusercontent.com/14146754/253714036-36f1eb76-d06f-45f9-8880-58bf558f31cd.png) 已经很注意yaml文件的编码和空白字符了，但还是报错
> > 其他功能都登陆正常
> 
> 这个功能当时我只在本地做了测试，感觉是添加的参数好像只能用一次而且有过期限制。 新版本通过登录 `refresh` 接口重新获取这些参数。
> 
> https://github.com/starudream/douyu-task/releases/tag/v2.0.0 这个版本用 `douyu-task run login` 试一下看看。

  assigns:
    # { room, count, all }
    # room 直播间号，如果是 0 的话，对已有牌子的直播间分别送上 count 数量的荧光棒
    # count 荧光棒数量
    # all 是否全部分配，建议最后一个直播间设置为 all: true，这样就可以把剩余的荧光棒全部分配出去
    - count: 1
    - room: 99999
      count: 10
    - room: 9999
      all: true

这两个count有什么不同呢

**Comment by starudream** [comment]
第一个 count 对应的 room 是空（等价于 0），会执行每个有牌子的直播间送 1 根荧光棒
第二个 count 对用的 room 是 99999，会执行 99999 直播间送 10 根荧光棒
最后一个 all 是 true，会把剩余的荧光棒全部送给 9999
