### ISSUE TITLE
判断礼物过期时间错误

### ISSUE THREAD

**Issue by D3ee** [starudream/douyu-task#28]
2023-07-26T13:21:01.170+08:00 INF renewal gifts today not expired, skip version=v2.0.2
凌晨定时器运行刷新获取的，赠送礼物定时器跑起来，提示荧光棒时间不是今天过期
![image](https://github.com/starudream/douyu-task/assets/37684328/d66161b5-0ea5-494a-ba48-d3220f2f211d)

**Comment by starudream** [comment]
我以为和超粉团一样是0点过期的，我改一下判断时间。 

https://github.com/starudream/douyu-task/releases/tag/v2.0.3

**Comment by D3ee** [comment]
ltp0这个参数app端有嘛？可以使用它，然后PC端不受影响嘛

**Comment by starudream** [comment]
受影响的应该只有 `websocket` 登录会踢掉线，这个机制没办法改变（就像你手机电脑打开同一个直播间也会提示异地登录）。

`douyu.room` 这个参数你改成其他的直播间（不是现在观看的直播间）就不会被踢了，应该也不会影响每日获取荧光棒。

**Comment by D3ee** [comment]
> 

可是webSocket会一直连接嘛？比如凌晨1点通过websocket获取，那我下午1点再进入直播间应该是只有一个设备登录此直播间了吧？

**Comment by starudream** [comment]
websocket 不会一直连接，你设置了凌晨一点，只会在那个时间尝试登录一次，最多也就 10 秒钟，之后就关闭连接了。

**Comment by D3ee** [comment]
> websocket 不会一直连接，你设置了凌晨一点，只会在那个时间尝试登录一次，最多也就 10 秒钟，之后就关闭连接了。

关闭连接后，我再次打开相同直播间就会提示未登录，感觉不是同一时间登录相同房间导致的

**Comment by starudream** [comment]
发现了这个问题，我猜大概率是一个 `LTP0` 只能有一个 `acf_auth`，凌晨一点跑这个任务会重新获取一个 `acf_auth` 导致电脑上之前的 `acf_auth` 失效，清空 `acf_auth` 就会自动跳转，然后自动登录成功。

**Comment by starudream** [comment]
其实可以把 `douyu.com` 下的所有 `cookie` 都清除，然后重新登录一下，获取一个新的 `LTP0`。

**Comment by D3ee** [comment]
> 其实可以把 `douyu.com` 下的所有 `cookie` 都清除，然后重新登录一下，获取一个新的 `LTP0`。

也就是正常浏览器正常用。开启一个无痕模式获取新的LTP0这样就互不干扰了？

**Comment by starudream** [comment]
或者浏览器开个无痕模式，在无痕模式下登录，然后配置文件里就填写无痕模式的 `LTP0`，就不会影响正常浏览器看直播了

**Comment by starudream** [comment]
> > 其实可以把 `douyu.com` 下的所有 `cookie` 都清除，然后重新登录一下，获取一个新的 `LTP0`。
> 
> 也就是正常浏览器正常用。开启一个无痕模式获取新的LTP0这样就互不干扰了？

是的

**Comment by D3ee** [comment]
> > > 其实可以把 `douyu.com` 下的所有 `cookie` 都清除，然后重新登录一下，获取一个新的 `LTP0`。
> > 
> > 
> > 也就是正常浏览器正常用。开启一个无痕模式获取新的LTP0这样就互不干扰了？
> 
> 是的

谢谢大佬~
