### ISSUE TITLE
每日刷新背包偶尔会登陆超时

### ISSUE THREAD

**Issue by u2shana** [starudream/douyu-task#29]
![image](https://github.com/starudream/douyu-task/assets/14146754/abdabda5-34de-4341-86b4-65ab03a8cf59)
而且好像没有重试策略

**Comment by starudream** [comment]
这个问题我也出现过，会出现 timeout，但是也不清楚哪边的问题。

重试有空我给加上，暂时可以修改 crontab 解决进行尝试。

```yaml
cron:
  refresh: "0 10 */2 * * *"
```

**Comment by starudream** [comment]
之前 [v2.0.4](https://github.com/starudream/douyu-task/releases/tag/v2.0.4) 版本加了重试之后，每日任务没遇见失败的情况。

---

通过websocket登录授权，前后发同样的数据包，会有极低概率出现返回的数据没有登录状态和匿名访问直播间一样。
目前通过重试能解决这种情况。
